-- Check lookahead condition

-- Bizmates:
-- Check if any Bizmates charges exist where end_date is day 1-2
-- AND ticket end_datetime does NOT extend past the 1st of that month
-- (meaning no next-month row would be generated by the CTE)
SELECT
    sp.charge_id,
    sp.student_id,
    sp.product_id,
    sp.start_date,
    sp.end_date,
    MAX(t.end_datetime) AS max_ticket_end,
    DATE_FORMAT(sp.end_date, '%Y-%m-01') AS end_date_month_start
FROM trn_student_product sp
JOIN trn_ticket t ON t.student_product_id = sp.id
JOIN mst_product p ON p.product_id = sp.product_id AND p.lesson_type = 2
WHERE DAY(sp.end_date) IN (1, 2)
    AND sp.status IN (0, 1)
    AND t.ticket_type = 3
    AND sp.product_id NOT IN (61, 62, 63, 64)
GROUP BY sp.charge_id, sp.student_id, sp.product_id, sp.start_date, sp.end_date
HAVING MAX(t.end_datetime) <= DATE_FORMAT(sp.end_date, '%Y-%m-01')
LIMIT 20;


-- Zipan (same query, different DB):
SELECT
    sp.charge_id,
    sp.student_id,
    sp.product_id,
    sp.start_date,
    sp.end_date,
    MAX(t.end_datetime) AS max_ticket_end,
    DATE_FORMAT(sp.end_date, '%Y-%m-01') AS end_date_month_start
FROM trn_student_product sp
JOIN trn_ticket t ON t.student_product_id = sp.id
JOIN mst_product p ON p.product_id = sp.product_id AND p.lesson_type = 2
WHERE DAY(sp.end_date) IN (1, 2)
    AND sp.status IN (0, 1)
    AND t.ticket_type = 3
    AND sp.product_id NOT IN (61, 62, 63, 64)
GROUP BY sp.charge_id, sp.student_id, sp.product_id, sp.start_date, sp.end_date
HAVING MAX(t.end_datetime) <= DATE_FORMAT(sp.end_date, '%Y-%m-01')
LIMIT 20;



-- Check what contract types exist in Zipan for monthly plans
SELECT
    sp.contract_type,
    CASE sp.contract_type
        WHEN 0 THEN 'B2C (PayPal)'
        WHEN 1 THEN 'B2B'
        WHEN 2 THEN 'B2B2C'
        WHEN 3 THEN 'Partner'
    END AS contract_type_name,
    CASE 
        WHEN c.order_no IS NULL THEN 'NULL'
        ELSE 'Has order_no'
    END AS order_no_status,
    COUNT(*) AS charge_count
FROM trn_student_product sp
JOIN trn_charge c ON c.id = sp.charge_id
WHERE sp.product_id IN (16, 17, 18)
    AND sp.status IN (0, 1)
GROUP BY sp.contract_type, order_no_status
ORDER BY sp.contract_type;
